[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
]

[profile.release]
lto = true
debug = 1
incremental = false

[patch.crates-io]
crossfont = { git = "https://github.com/zenixls2/crossfont", branch = "ligature" }
#freetype = { git = "https://github.com/servo/rust-freetype.git" }
